theme = "catppuccin_mocha"

[editor]
true-color = true
line-number = "relative"
cursorline = true
color-modes = true
auto-completion = true
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "warning"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
"C-[" = "jump_backward"
"C-]" = "jump_forward"
