theme = "catppuccin_mocha"

[editor]
true-color = true
line-number = "relative"
cursorline = true
color-modes = true
auto-completion = true
auto-save = true
bufferline = "always" # バッファをタブみたいに見えるようにする

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "warning"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
"X" = ["extend_line_up", "extend_to_line_bounds"]
"C-[" = "jump_backward"
"C-]" = "jump_forward"
"H" = ":buffer-previous"
"L" = ":buffer-next"

"C-j" = ["scroll_down", "move_line_down"]
"C-k" = ["scroll_up", "move_line_up"]

"C-r" = ":rla"

# lazygitを起動
"C-g" = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

# yaziを起動
"C-y" = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

[keys.insert]
j = { j = "normal_mode" } # "jj"でNormal Modeへ移行
